name: Update Playlist

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        run: python update_playlist.py

      - name: Save Changes
        run: |
      - name: Save Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add merged_playlist.m3u
          git commit -m "Playlist Updated: $(date)" || echo "No changes to commit"
          git push


