name: Update Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # প্রতি ৬ ঘণ্টা পর পর

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # এটি থাকা বাধ্যতামূলক
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python merge_script.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          git commit -m "Update playlist" || exit 0
          git push
